### ISSUE TITLE
[Feature request] Modify the homepage

### ISSUE THREAD

**Issue by iam-py-test** [troysjanda/MyBlockLists#3]
https://github.com/troysjanda/MyBlockLists/blob/f61bed2c89d126da320cc46177aadf400ffc078c/UBOXPI#L5
points to the raw version of the list as the homepage for uBo.
However, uBo already allows users to view the raw url, so (in my opinion) it should be updated to link to [this repo](https://github.com/troysjanda/MyBlockLists).
Thanks for making the internet a little less annoying!

**Comment by troysjanda** [comment]
will be fixed in next update. ETA 1500 hours PST.

**Comment by troysjanda** [comment]
Issues resolved with the new update. Thanks for the input.
